### ISSUE TITLE
Consider updating the installation instructions with `brew tap nvie/tap` step

### ISSUE THREAD

**Issue by kkom** [nvie/git-toolbelt#10]
Hey @nvie!

I'm trying to install it on a Mac using brew, but I'm getting this error:

```
Highgarden:~ kkom$ brew update && brew upgrade && brew install moreutils && brew install nvie/tap/git-toolbelt
Already up-to-date.
Warning: moreutils 0.63 is already installed and up-to-date
To reinstall 0.63, run `brew reinstall moreutils`
Error: No available formula with the name "nvie/tap/git-toolbelt" 
Please tap it and then try again: brew tap nvie/tap
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
```

Any idea what could be going on? Any more debugging info I can give you?

**Comment by kkom** [comment]
Oups, it was my fault, I didn't read the instructions carefully... Facepalm!

**Comment by kkom** [comment]
It might be a good idea however to update the instructions on the website to be this?

```
brew install moreutils
brew tap nvie/tap
brew install nvie/tap/git-toolbelt
```

If most people wanting to install this tool will need to tap `nvie/tap`? (Not sure if it is the case.)

I'll reopen the task and let you make the decision! :)

**Comment by nvie** [comment]
Oh, thanks @kkom ! I honestly thought that brew would automatically tap it if you use the long-form tap spec (i.e. if you use `nvie/tap/xxx`, brew would automatically first do `brew tap nvie/tap` and then run `brew install nvie/tap/git-toolbelt`). Apparently not the case (anymore?) ?

**Comment by kkom** [comment]
> Apparently not the case (anymore?) ?

Definitely not for me!

**Comment by nvie** [comment]
Hmm, that's no good then! I've just updated the instructions in the README. Thanks for reporting, @kkom !
