### ISSUE TITLE
Git recent-branches date range and default value

### ISSUE THREAD

**Issue by jonathanchu** [nvie/git-toolbelt#17]
When using `git recent-branches`, it doesn't _seem_ to be displaying branches based on a date range, even the default.  It just shows all the branches.

From the `git recent-branches` usage message:
> Shows a list of branches that have been modified since the specified date range. Defaults to '1.week.ago'.

Is this just missing the date range being passed in or was this some inherent behavior of `for-each-ref --sort=` in an older version of git?

**Comment by jonathanchu** [comment]
BTW thank you for your work with all of this! Super useful toolset and I learned a lot about git from the commands I wasn't familiar with! 🍻  😻

**Comment by nvie** [comment]
Thanks for reporting this. This has been fixed in 13658f8b8a454ee848091ffcfc24c9fbc4fbc730 now. It was just a copy/pasta error from some other command, I guess.

**Comment by jonathanchu** [comment]
Ah! I thought it was maybe some magic behavior of an older version of git since I only just learned about `for-each-ref` the other day.

**Comment by nvie** [comment]
Nope, good catch! Turns out someone reads the usage messages after all 😜
