### ISSUE TITLE
Replace git-assume / git-unassume / git-show-assumed with skip-worktree equivalents

### ISSUE THREAD

**Issue by akeeton** [nvie/git-toolbelt#28]
According to the accepted answer of the StackOverflow question [Git - Difference Between 'assume-unchanged' and 'skip-worktree'][1], _skip-worktree_ should be used instead of _assume-unchanged_ in cases where the goal is to "hide" a file.

The [git-assume / git-unassume / git-show-assumed][2] section expresses that goal but the tools are named and implemented based on _assume-unchanged_ instead of _skip-worktree_:
> Git supports marking files "assumed unchanged", meaning any change in the file
> locally will not be shown in status reports, or be added when you stage all
> files.  This feature can be useful to toggle some switches locally, or
> experiment with different settings, without running the risk of accidentally
> committing this local data (that should remain untouched in the repo).

  [1]: https://stackoverflow.com/questions/13630849/git-difference-between-assume-unchanged-and-skip-worktree
  [2]: https://github.com/nvie/git-toolbelt#git-assume--git-unassume--git-show-assumed

**Comment by nvie** [comment]
Interesting!  It seems indeed to more closely resemble what I wanted here.  Thanks for the pointer. I'll read up a bit more on this soon and try to change this in the next release 🙏

**Comment by nvie** [comment]
Thanks for this pointer! I've just added and released (as v1.4.0) a new suite of commands for this: `git-skip`, `git-unskip` and `git-show-skipped`, which make the previous assume-based commands deprecated.   Thank you for the contribution!
