### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TeddyDD** [nvie/git-toolbelt#31]
Hi. I'd like to package git-toolbelt for Void Linux, but it's currently impossible due to lack of license.

> Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. 

Could you consider choosing some open source license for this project?
Thanks

https://choosealicense.com/

**Comment by nvie** [comment]
Thanks for pointing this out! Just added one 🙏

**Comment by TeddyDD** [comment]
Thanks again!

**Comment by TeddyDD** [comment]
Could you please bump version as well? I need LICENSE file to be in release tarball :)

**Comment by nvie** [comment]
Yep! Just did @ https://github.com/nvie/git-toolbelt/releases/tag/v1.4.1
