### ISSUE TITLE
'git-active-branches' relies on third-party 'ifne' utility

### ISSUE THREAD

**Issue by ernstki** [nvie/git-toolbelt#33]
`git-active-branches` is making use of `ifne` from Joey Hess' [moreutils](https://joeyh.name/code/moreutils/).

This is fine for Linux people with `moreutils` just a `sudo` command away, and Mac people with Homebrew or MacPorts already set up, but creates a bit of a challenge if someone is using, say, Git for Windows (#29).

**Comment by pmlandwehr** [comment]
Has this entirely purged the dependency on `moreutils`? If so, the README needs a tweak removing a mention of it. (I can do a pull, if that helps.)

**Comment by nvie** [comment]
> Has this entirely purged the dependency on `moreutils`? If so, the README needs a tweak removing a mention of it. (I can do a pull, if that helps.)

I believe so! Please feel free to :)
