### ISSUE TITLE
git-local-branches returns "(HEAD detached at [...]"

### ISSUE THREAD

**Issue by asford** [nvie/git-toolbelt#43]
`git-local-branches` returns the informative `(HEAD detached at [...]` entry shown by `git branch` when run in a detached head state. This causes error in downstream tools, which (I believe) expect `git-local-branches` to only return valid branch names. For example, `git cleanup -s` errors out if one checks out `origin/master` to "hop off" a feature branch after an upstream squash-merge.

Repro:

```
~/asford/git-toolbelt$ ./git-local-branches
local_branch_detached
master

~/asford/git-toolbelt$ git checkout origin/master
Note: switching to 'origin/master'.

You are in 'detached HEAD' state [...]

~/asford/git-toolbelt$ ./git-local-branches
(HEAD detached at origin/master)
local_branch_detached
master
```

**Comment by nvie** [comment]
This is now fixed as of [v1.5.1](https://github.com/nvie/git-toolbelt/releases/tag/v1.5.1) – thanks for reporting and fixing!
