### ISSUE TITLE
how do I use in Ubuntu?

### ISSUE THREAD

**Issue by firecentaur** [nvie/git-toolbelt#5]
hi there, how do I install this in ubuntu?

**Comment by nirajkaushal** [comment]
Hello @firecentaur,  

**Follow these steps to make it works in Ubuntu**

1.  Install `brew` in Ubuntu
2.  Install  `moreutils` and `git-toolbelt` as suggested in readme file
3.  Add paths for these tools in `.bashrc` file, to edit type `gedit ~/.bashrc`
4.  Add this line `export PATH="/home/linuxbrew/.linuxbrew/opt/coreutils/libexec/gnubin:$PATH"`
5.  Add this line `export PATH="/home/linuxbrew/.linuxbrew/opt/moreutils/bin:$PATH"` for moreutils 
6.  Add this `export PATH="/home/linuxbrew/.linuxbrew/opt/git-toolbelt/bin:$PATH"` for git-toolbelt 
7.  Save and close `.bashrc` file then type `source  ~/.bashrc`

That's it, Now you can use these commands :smile: 

Thanks @nvie for creating awesome tools :+1:
