### ISSUE TITLE
Git cleanup by default removes remote branches

### ISSUE THREAD

**Issue by guiccbr** [nvie/git-toolbelt#54]
I was surprised that after running cleanup (without reading the docs carefully), all of the merged branches were also removed in the remote. Even branches that were not created by me.

It seems to me that the default should be local-only to make sure that we don't mess up with branches that other devs may be relying on.

**Comment by nvie** [comment]
Yeah, that is a good point. If you feel like adding a flag for that (perhaps `-r`?), I'd be happy to merge that in! 🙏

**Comment by guiccbr** [comment]
Tks, @nvie , there is already a [flag](https://github.com/nvie/git-toolbelt/blob/d5335130edfcb32c32cdd9fdf8cc144265530724/git-cleanup#L26)`-l`, that has the opposite behavior. Do you think that it's ok to rename it to -r and make the adjustments? If so I can send a pr.

**Comment by nvie** [comment]
I wouldn't mind making them both explicit, so that just invoking `git cleanup` would show the usage, and it would ask you to specify `-l`, `-r`, or both.

**Comment by nvie** [comment]
I wouldn't mind making them both explicit, so that just invoking `git cleanup` would show the usage, and it would ask you to specify `-l`, `-r`, or both.

**Comment by riotrah** [comment]
Another thought though - how hard might it be to make a variant/default that only deletes _your_ branches remotely, instead of any?

**Comment by nvie** [comment]
Thanks for the ping, @riotrah! I just implemented the behavior [I suggested earlier](https://github.com/nvie/git-toolbelt/issues/54#issuecomment-979764447), which I've released as [v1.8.0](https://github.com/nvie/git-toolbelt/releases/v1.8.0) just now.
