### ISSUE TITLE
What tool did you use to draw your pictures in Git model

### ISSUE THREAD

**Issue by Crandy** [nvie/git-toolbelt#55]
Hi，Nvie， I really want to konw, what tool did you use to draw the pictures of Git model in your article "A successful Git branching model" , thank you.

**Comment by jonathanchu** [comment]
Hi @Crandy - I believe he used Apple Keynote and you can find the source at the bottom of the [original article](https://nvie.com/posts/a-successful-git-branching-model/#summary) or here directly: http://github.com/downloads/nvie/gitflow/Git-branching-model-src.key.zip.

**Comment by Crandy** [comment]
@jonathanchu ok, I'll have a try, thank you.

**Comment by nvie** [comment]
Correct! ❤️
