### ISSUE TITLE
About git current-branch in README

### ISSUE THREAD

**Issue by duongdominhchau** [nvie/git-toolbelt#60]
The very first command I saw in the README is `git current-branch` which is aliased to `git rev-parse --abbrev-ref HEAD`

> Returns the name of the current branch, if any. Why doesn't this come with git?

I think this line is written before Git 2.22, today Git have `--show-current` flag for this purpose. I think the built-in way is intuitive enough to deprecate the `current-branch` alias for users having access to the latest Git. What do you think?

A disclaimer: I'm not a user of this tool, just passing by this interesting repo.

**Comment by nvie** [comment]
> I think this line is written before Git 2.22, today Git have `--show-current` flag for this purpose. I think the built-in way is intuitive enough to deprecate the `current-branch` alias for users having access to the latest Git. What do you think?

Ah yes, definitely. For normal everyday command line uses this script may indeed no longer really be necessary.

One notable difference is that `git current-branch` will exit with a non-zero exit code in case you aren't on a branch (for example, if you're in the middle of a rebase or you have a headless checkout). I noticed that `git branch --show-current` doesn't do that and instead exits with a 0 exit code, but simply doesn't return anything on stdout.

So I'm inclined to just keep the script (for scripting purposes) and not change it.

Thanks for the ping about this, though! Always happy to deprecate stuff if it's no longer needed or there is a better default way.
