### ISSUE TITLE
About `git push-current`

### ISSUE THREAD

**Issue by duongdominhchau** [nvie/git-toolbelt#61]
`git push` is short and simple, so I assume `git push-current` is your solution to the verbosity of the `git push -u origin <branch>` on first push. In that case, may I suggest an alternative, just:

```sh
git config --global push.default current
git config --global push.autoSetupRemote true
```

then use `git push` everywhere.

The config above requires Git 2.37 or newer.

**Comment by duongdominhchau** [comment]
Ouch, just saw your comment on the other issue. I see, this is still useful for scripting, closing it then.

**Comment by nvie** [comment]
Also, `git push` (used to?) push _all_ local branches to the remote. This was mostly added to push out only the current branch, (whatever it is currently).

**Comment by duongdominhchau** [comment]
Maybe I'm too young to experience that issue. I started using Git about 7 years ago.

Found something on [StackOverflow](https://stackoverflow.com/a/34927638) suggesting `push.default = matching` is the culprit (which is no longer the default since Git 2.0), guess this is what you are talking about.
