### ISSUE TITLE
git-active-branches gives error if branch name clashes with file/directory name

### ISSUE THREAD

**Issue by delfador** [nvie/git-toolbelt#64]
If a branch name is identical to a file/directory, you'll get the error
```fatal: ambiguous argument 'branch_name': both revision and filename```

I suggest appending `--` to the `git` command.

A similar error occurs when there's a clash with a tag name. I don't know an easy solution for that.

**Comment by nvie** [comment]
Thanks for reporting @delfador! The fix for this has now been published as [v1.9.2](https://github.com/nvie/git-toolbelt/releases/tag/v1.9.2).
