### ISSUE TITLE
git-merged does not use git-main-branch

### ISSUE THREAD

**Issue by kivra-adalin** [nvie/git-toolbelt#65]
When running `git-merged` (and `git-unmerged`) in a repository that has the main branch set to `main`:

```console
$ git merged
fatal: malformed object name master
```

These commands should probably use `git-main-branch` internally instead of hard coding `master`?

**Comment by nvie** [comment]
Hi Adam, thanks for reporting this issue! It's now fixed and published as [v1.9.3](https://github.com/nvie/git-toolbelt/releases/tag/v1.9.3) 🙏 !
