### ISSUE TITLE
Windows use

### ISSUE THREAD

**Issue by iancampelo** [nvie/git-toolbelt#9]
Hi, how can I use it on Windows?

**Comment by nvie** [comment]
This project currently relies heavily on Unix tools, and I would like to keep it light. I'm not sure how to port any of this over to Windows as I'm not an expert and don't own a Windows machine. If there is a simple and maintainable way of adding support for that, I'm happy to accept contributions.

**Comment by maherm** [comment]
Git for Windows ships with Git Bash, a bash emulation built on MSYS2. So git-toolbelt runs pretty much out-of-the-box. You just need to extract the scripts and add the directory to your path in bash.

- Download the scripts
- in the folder containing the scripts, run git bash
- `echo -e "\nPATH=\$PATH;\"$(cmd //c cd)\"" >> ~/.bashrc`

I haven't yet tried all of the tools, but the ones I tried worked flawlessly.

@nvie: maybe you could consider submitting git-toolbelt to chocolatey, a widely spread package manager for windows
